"""empty message

Revision ID: a8f39a11af9f
Revises: d3536b755ac3
Create Date: 2021-01-01 23:59:06.609383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f39a11af9f'
down_revision = 'd3536b755ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
